name: Kwiki-Keywords
version: 0.13
abstract: Keywords for Kwiki
author: Chris Dent <cdent@cpan.org>
license: perl
distribution_type: module
requires:
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
