name: Kwiki-Keywords
version: 0.11
abstract: Keywords for Kwiki
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
